version: '3'
services:
  # Setup MySQL
  api_node_graphql_mysql_db:
    image: 'mysql:5.7' 
    ports:
      - 3307:3306 
    restart: always # This will make sure that the container comes up post unexpected shutdowns
    env_file:
      - ./api-node-graphql-mysql/.env.docker
    volumes:
      - api-node-graphql-mysql-db-volume:/var/lib/mysql

  # Setup api-node-graphql-mysql api
  api-node-graphql-mysql:
    build:
      context: './api-node-graphql-mysql'
      args:
        ENVIRONMENT_NAME: docker
    ports:
      - 9001:9000
    env_file:
      - ./api-node-graphql-mysql/.env.docker
    environment:
      ENVIRONMENT_NAME: docker


  # Setup Redis
  redis:
    image: 'redis:6-alpine'
    ports:
      - 6379:6379
    # Default command that redis will execute at start
    command: ['redis-server']

  # Setup fe-next-web web
  fe-next-web:
    build:
      context: './fe-next-web'
    ports:
      - 3000:3000
    env_file:
      - ./fe-next-web/.env.docker

# Setup Volumes
volumes:
  api-node-graphql-mysql-db-volume:
