version: '3'
services:
  # Setup PostgreSQL
  api_02_node_graphql_pg_db:
    image: 'postgres:15' 
    ports:
      - 5432:5432 
    restart: always # This will make sure that the container comes up post unexpected shutdowns
    env_file:
      - ./api02-node-graphql-pg/.env.docker
    volumes:
      - api02-node-graphql-pg-db-volume:/var/lib/postgresql/data

  # Setup api02-node-graphql-pg api
  api02-node-graphql-pg:
    build:
      context: './api02-node-graphql-pg'
      args:
        ENVIRONMENT_NAME: docker
    ports:
      - 9000:9000
    env_file:
      - ./api02-node-graphql-pg/.env.docker
    environment:
      ENVIRONMENT_NAME: docker


  # Setup PostgreSQL
  api_01_node_hapi_pg_db:
    image: 'postgres:15' 
    ports:
      - 5433:5432 
    restart: always # This will make sure that the container comes up post unexpected shutdowns
    env_file:
      - ./api01-node-hapi-pg/.env.docker
    volumes:
      - api01-node-hapi-pg-db-volume:/var/lib/postgresql/data

  # Setup api01-node-hapi-pg api
  api01-node-hapi-pg:
    build:
      context: './api01-node-hapi-pg'
      args:
        ENVIRONMENT_NAME: docker
    ports:
      - 9001:9000
    env_file:
      - ./api01-node-hapi-pg/.env.docker
    environment:
      ENVIRONMENT_NAME: docker


  # Setup Redis
  redis:
    image: 'redis:6-alpine'
    ports:
      - 6379:6379
    # Default command that redis will execute at start
    command: ['redis-server']

  # Setup fe02-next-js-web web
  fe02-next-js-web:
    build:
      context: './fe02-next-js-web'
    ports:
      - 3000:3000
    env_file:
      - ./fe02-next-js-web/.env.docker

  # Setup fe01-react-js-web web
  fe01-react-js-web:
    build:
      context: './fe01-react-js-web'
    ports:
      - 3001:3000
    env_file:
      - ./fe01-react-js-web/.env.docker

# Setup Volumes
volumes:
  api02-node-graphql-pg-db-volume:
  api01-node-hapi-pg-db-volume:
