version: '3'
services:
  # Setup PostgreSQL
  api_node_hapi_pg_db:
    image: 'postgres:15' 
    ports:
      - 5434:5432 
    restart: always # This will make sure that the container comes up post unexpected shutdowns
    env_file:
      - ./api-node-hapi-pg/.env.docker
    volumes:
      - api-node-hapi-pg-db-volume:/var/lib/postgresql/data

  # Setup api-node-hapi-pg api
  api-node-hapi-pg:
    build:
      context: './api-node-hapi-pg'
      args:
        ENVIRONMENT_NAME: docker
    ports:
      - 9002:9000
    env_file:
      - ./api-node-hapi-pg/.env.docker
    environment:
      ENVIRONMENT_NAME: docker


  # Setup Redis
  redis:
    image: 'redis:6-alpine'
    ports:
      - 6379:6379
    # Default command that redis will execute at start
    command: ['redis-server']

  # Setup fe-react-graphql-web web
  fe-react-graphql-web:
    build:
      context: './fe-react-graphql-web'
    ports:
      - 3001:3000
    env_file:
      - ./fe-react-graphql-web/.env.docker

# Setup Volumes
volumes:
  api-node-hapi-pg-db-volume:
