name: CI fe-react-graphql-web
on:
  push:
    branches: ["master", "develop", "qa"]
    paths: "fe-react-graphql-web/**"
  pull_request:
    paths: "fe-react-graphql-web/**"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./fe-react-graphql-web
    strategy:
      matrix:
        node-version: [16.14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ./fe-react-graphql-web/package.json

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build:dev

      - name: Test
        run: yarn test
