name: CI service-picker-example
on:
  push:
    branches: ["master", "develop", "qa"]
  pull_request:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the logs
        run: echo SERVICE PICKER, service-picker-example
